name: Generar APK Fabrica

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    name: Compilar Android
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Descargar CÃ³digo
        uses: actions/checkout@v4

      - name: â˜• Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle' # Esto acelera las prÃ³ximas compilaciones

      - name: ğŸ¦ Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'

      - name: ğŸ“¦ Descargar LibrerÃ­as
        run: flutter pub get

      - name: ğŸ—ï¸ Generar Archivos (Drift/Riverpod)
        run: dart run build_runner build --delete-conflicting-outputs

      # CAMBIO CLAVE: Usamos este comando para evitar el error de "No such file"
      - name: ğŸ”¨ Compilar APK (Release)
        run: flutter build apk --release --no-pub
        working-directory: . 

      - name: ğŸ“¤ Subir APK a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-fabrica-release
          path: build/app/outputs/flutter-apk/app-release.apk
