name: Generar APK Fabrica

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite forzar la compilaciÃ³n con un botÃ³n

jobs:
  build:
  
  - name: ğŸ”‘ Dar permisos al ejecutable de Gradle
        run: chmod +x android/gradlew
      - name: ğŸ”¨ Compilar APK (Release)
        run: flutter build apk --release

    steps:
      - name: ğŸ“¥ Descargar CÃ³digo
        uses: actions/checkout@v4

      - name: â˜• Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: ğŸ¦ Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0' # VersiÃ³n estable recomendada

      - name: ğŸ“¦ Descargar LibrerÃ­as
        run: flutter pub get

      # ESTE PASO ES CRÃTICO: Genera el cÃ³digo de la base de datos
      - name: ğŸ—ï¸ Generar Archivos (Drift/Riverpod)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: ğŸ”¨ Compilar APK (Release)
        run: flutter build apk --release

      - name: ğŸ“¤ Subir APK a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-fabrica-release
          path: build/app/outputs/flutter-apk/app-release.apk
